__all__ = [ 'ABORTED', 'OK',
            'FAILURE_IN_EXECUTION', 'XML_FILES_FOLDER_NOT_FOUND', 'SETTINGS_FOLDER_NOT_FOUND',
            'MODEL_NOT_FOUND', 'INVALID_ARGUMENT', 'INVALID_NUMBER_OF_ARGUMENTS', 'LED_NAME_NOT_FOUND_IN_MODEL', 'KEY_NAME_NOT_FOUND_IN_MODEL',
            'CAMERA_CONNECTION_FAILURE', 'CAMERA_TIMEOUT_RECEPTION', 'CAMERA_TIMEOUT_STOPPED',
            'SERIALPORT_CONNECTION_FAILURE', 'SERIALPORT_TIMEOUT_RECEPTION',
            'LEDS_TEST_NOT_PASSED', 'LEDS_TEST_NOT_TURN_ALL_ON', 'LEDS_TEST_NOT_TURN_ALL_OFF', 'LEDS_TEST_COLOUR_SEQUENCE_ERROR', 'LEDS_TEST_STATE_SEQUENCE_ERROR', 'LEDS_TEST_NO_CHANGES_TIMEOUT',
            'KEYS_TEST_NOT_PASSED', 'KEYS_TEST_KEY_DETECTED_CONSECUTIVELLY', 'KEYS_TEST_KEY_DETECTED_TWO_TIMES', 'KEYS_TEST_SEQUENCE_ERROR', 'KEYS_TEST_NO_CHANGES_TIMEOUT',
            'DISPLAY_TEST_NOT_PASSED', 'DISPLAY_TEST_PIX_NOT_PASSED', 'DISPLAY_TEST_CHR_NOT_PASSED', 'DISPLAY_TEST_PAL_NOT_PASSED', 'DISPLAY_BAD_MODEL_PARAMETERS',
            'BOOTLOADER_TEST_NOT_PASSED',
            'BOARD_INFO_TEST_NOT_PASSED',
            'ALIGHT_TEST_NOT_PASSED'
           ]

ABORTED = -1
OK = 0

FAILURE_IN_EXECUTION = 10
XML_FILES_FOLDER_NOT_FOUND = 11
SETTINGS_FOLDER_NOT_FOUND = 12

MODEL_NOT_FOUND = 20
INVALID_ARGUMENT = 21
INVALID_NUMBER_OF_ARGUMENTS = 22
LED_NAME_NOT_FOUND_IN_MODEL = 23
KEY_NAME_NOT_FOUND_IN_MODEL = 24

CAMERA_CONNECTION_FAILURE = 30
CAMERA_TIMEOUT_RECEPTION = 31
CAMERA_TIMEOUT_STOPPED = 32

SERIALPORT_CONNECTION_FAILURE = 40
SERIALPORT_TIMEOUT_RECEPTION = 41

LEDS_TEST_NOT_PASSED = 50
LEDS_TEST_NOT_TURN_ALL_ON = 51
LEDS_TEST_NOT_TURN_ALL_OFF = 52
LEDS_TEST_COLOUR_SEQUENCE_ERROR = 53
LEDS_TEST_STATE_SEQUENCE_ERROR = 54
LEDS_TEST_NO_CHANGES_TIMEOUT = 55

KEYS_TEST_NOT_PASSED = 60
KEYS_TEST_KEY_DETECTED_CONSECUTIVELLY = 61
KEYS_TEST_KEY_DETECTED_TWO_TIMES = 62
KEYS_TEST_SEQUENCE_ERROR = 63
KEYS_TEST_NO_CHANGES_TIMEOUT = 64

DISPLAY_TEST_NOT_PASSED = 70
DISPLAY_TEST_PIX_NOT_PASSED = 71
DISPLAY_TEST_CHR_NOT_PASSED = 72
DISPLAY_TEST_PAL_NOT_PASSED = 73
DISPLAY_BAD_MODEL_PARAMETERS = 74

BOOTLOADER_TEST_NOT_PASSED = 80

BOARD_INFO_TEST_NOT_PASSED = 90

ALIGHT_TEST_NOT_PASSED = 100