__all__ = ['NTIMEOUT_MENUS', 'CAM_LEDS', 'CAM_DISPLAY', 
           'TYPE_SET', 'TYPE_TEST', 'TYPE_HELP', 'TEST_TYPE_BUTTONS', 'TEST_TYPE_BOOTLOADER_INFO', 
           'TEST_TYPE_BOARD_INFO', 'TEST_TYPE_ALIGHT', 'TEST_TYPE_LEDS', 'TEST_TYPE_DISPLAY'
           ,'NTIMEOUT_LIBRARY_SETTINGS']


NTIMEOUT_MENUS = 5

# Camaras
CAM_LEDS = 'Cam1'
CAM_DISPLAY = 'Cam2'

# Comands
TYPE_SET = 'set'
TYPE_TEST = 'test'
TYPE_HELP = 'help'
TEST_TYPE_BUTTONS = '-key'
TEST_TYPE_BOOTLOADER_INFO = '-bootloader'
TEST_TYPE_BOARD_INFO = '-board'
TEST_TYPE_ALIGHT = '-alight'
TEST_TYPE_LEDS = '-led'
TEST_TYPE_DISPLAY = '-display'

# SETTINGS
NTIMEOUT_LIBRARY_SETTINGS = 10