__all__ = ['TEST_BUTTONS_BEGIN', 'TEST_BUTTONSM', 'TEST_BUTTONS_OK', 'TEST_BOOT_LOADER_INFO_BEGIN', 
           'TEST_BOOT_LOADER_INFO_VERSION', 'TEST_BOOT_LOADER_INFO_DATE', 'TEST_BOOT_LOADER_INFO_ENTER',
           'TEST_BOOT_LOADER_INFO_CANCEL', 'TEST_BOARD_INFO_BEGIN', 'TEST_BOARD_INFO_BOARD', 
           'TEST_BOARD_INFO_SERIAL_NUMBER', 'TEST_BOARD_INFO_MANUFACTURE_DATE', 'TEST_BOARD_INFO_OPTION',
           'TEST_BOARD_INFO_REVISON', 'TEST_BOARD_INFO_EDITON', 'TEST_BOARD_INFO_LCD_TYPE', 
           'TEST_BOARD_INFO_CANCEL', 'TEST_BOARD_INFO_ENTER', 'TEST_ALIGHT_BEGIN', 'TEST_ALIGHT_ALIGHT', 
           'TEST_ALIGHT_GO_ON', 'TEST_ALIGHT_CANCEL', 'TEST_ALIGHT_ENTER', 'TEST_ALIGHT_OK', 
           'TEST_LEDS_BEGIN', 'TEST_LEDS_OK', 'TEST_LEDS_ENTER', 'TEST_LEDS_CANCEL', 'TEST_DISPLAY_BEGIN', 
           'TEST_DISPLAY_PIXEL', 'TEST_DISPLAY_CHAR', 'TEST_DISPLAY_COLOR', 'TEST_DISPLAY_OK', 
           'TEST_DISPLAY_ENTER', 'TEST_DISPLAY_CANCEL', 'TEST_WHATDOG_BEGIN', 'TEST_WHATDOG_ENTER', 
           'TEST_WHATDOG_CANCEL']


TEST_BUTTONS_BEGIN = 'TestKeys - Testing...'
TEST_BUTTONS = 'TestKeys - Pressed:'
TEST_BUTTONS_OK = 'TestKeys - Test OK'

TEST_BOOT_LOADER_INFO_BEGIN = 'TestBootloaderInfo - Testing...'
TEST_BOOT_LOADER_INFO_VERSION = 'TestBootloaderInfo - Version:' # 1.00.001
TEST_BOOT_LOADER_INFO_DATE = 'TestBootloaderInfo - Date:' # 20220408
TEST_BOOT_LOADER_INFO_ENTER = 'TestBootloaderInfo - Pressed: ENTER'
TEST_BOOT_LOADER_INFO_CANCEL = 'TestBootloaderInfo - Pressed: CANCEL'

TEST_BOARD_INFO_BEGIN = 'TestBoardInfo - Testing...'
TEST_BOARD_INFO_BOARD = 'TestBoardInfo - Board:' # MAP8061
BOARD = 'MAP8061'
TEST_BOARD_INFO_SERIAL_NUMBER = 'TestBoardInfo - Serial Number:' #AM038958
SERIAL_NUMBER = 'AM038958'
TEST_BOARD_INFO_MANUFACTURE_DATE = 'TestBoardInfo - Manufacture Date:' # 20230109
TEST_BOARD_INFO_OPTION = 'TestBoardInfo - Option:' # 1
TEST_BOARD_INFO_REVISON = 'TestBoardInfo - Revision:' # 2.0
TEST_BOARD_INFO_EDITON = 'TestBoardInfo - Edition:' # 2
TEST_BOARD_INFO_LCD_TYPE = 'TestBoardInfo - LCD Type:' # Tiamna TM057QHD01
TEST_BOARD_INFO_CANCEL = 'TestBoardInfo - Pressed: CANCEL'
TEST_BOARD_INFO_ENTER = 'TestBoardInfo - Pressed: ENTER'

TEST_ALIGHT_BEGIN = 'TestALight - Testing...'
TEST_ALIGHT_ALIGHT = 'TestALight - ALight' # 13669.36Lux || LATER: 709.68Lux (Covered)
TEST_ALIGHT_GO_ON = 'TestALight - Cover up the ALight Sensor and Press Enter to Continue'
TEST_ALIGHT_CANCEL = 'TestALight - Pressed: CANCEL'
TEST_ALIGHT_ENTER = 'TestALight - Pressed: ENTER'
TEST_ALIGHT_OK = 'TestALight - Test OK'


TEST_LEDS_BEGIN = 'TestLeds - Testing...'
TEST_LEDS_OK = 'TestLeds - Test OK'
TEST_LEDS_ENTER = 'TestLeds - Pressed: ENTER'
TEST_LEDS_CANCEL = 'TestLeds - Pressed: CANCEL'

TEST_DISPLAY_BEGIN = 'TestDisplay - Testing...'
TEST_DISPLAY_PIXEL = 'TestDisplay - Test PIX'
TEST_DISPLAY_CHAR = 'TestDisplay - Test CHR'
TEST_DISPLAY_COLOR = 'TestDisplay - Test PAL'
TEST_DISPLAY_OK = 'TestDisplay - Test OK'
TEST_DISPLAY_ENTER = 'TestDisplay - Pressed: ENTER'
TEST_DISPLAY_CANCEL = 'TestDisplay - Pressed: CANCEL'

TEST_WHATDOG_BEGIN = 'TestWdogHW - Testing...'
TEST_WHATDOG_ENTER = 'TestWdogHW - Pressed: ENTER'
TEST_WHATDOG_CANCEL = 'TestWdogHW - Pressed: CANCEL'
